services:
  eproject-backend:
    build:
      args:
        user: neon
        uid: 1000
      context: backend
      dockerfile: Dockerfile
    image: eproject-backend
    container_name: eproject-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www

  eproject-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_ROOT_DOMAIN=${NEXT_PUBLIC_API_ROOT_DOMAIN:-http://localhost:8383}
    environment:
      TZ: Asia/Ho_Chi_Minh
    image: eproject-frontend
    container_name: eproject-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8383:8383" # Cổng cho backend
    volumes:
      - ./backend:/var/www
      - ./nginx:/etc/nginx/conf.d



